### ISSUE TITLE
Expand city search to include geonames

### ISSUE THREAD

**Issue by nvkelso** [mapzen/map-ui#19]
When I search for Munich using this UI component (e.g. embeded into a map like https://tangrams.github.io/bubble-wrap/#16/31.7436/35.2063) the widget doesn't return anything. 

But using the Pelias search tool I do get a result (from GeoNames not WOF): http://pelias.github.io/compare/#/v1/search%3Ftext=munich

The tip says "Search for city", so it seems like adding `geonames` to the list of sources on this line would keep it "course" but expand the results:

- https://github.com/mapzen/scarab/blob/09b0e62b2b14f634b9084bead1b3a5cd21573de0/src/components/search/search.js#L46

Pelias is working to add functionality to allow alternate names (since Munich and München are both name values on the WOF record, but only Münich goes into Search index & logic now).

But Geonames still has more city coverage than WOF, so even with duplicates between the two I think it's better to find more things by changing this now.

Once the following WOF issues are completed than this could be limited to WOF again:

- [BLOCKED: Add GeoNames populated places not already in WOF #108](https://github.com/whosonfirst-data/whosonfirst-data/issues/108)

**Comment by louh** [comment]
Hey @nvkelso, I'm catching up on some issues now. After chatting with Julian it seems the trade off is that we increase coverage but reduce the quality of results. I tentatively agree that it seems worth while so that we can cover Munich (and similar localities). One question -- what does the timeline look like for including GeoNames data in WOF?

**Comment by louh** [comment]
Search box is using `geonames` as an additional source now.
